#+TITLE: 1: Preface
#+AUTHOR: GRC(扬眉剑)
#+LATEX_CLASS: ctexart
* github地址
https://github.com/gaorongchao/Perl6/tree/master/Using_perl6

所有后续更新都在github上进行，其他地方不做同步。
发现任何错误，或者不当的地方，请先到github查看是否改正。
如果没有请留言。或者邮件交流：rongchaogao@gmail.com
* 第一章：前言
Perl6是这样一门编程语言，在整个程序的完整周期中，在各个不同的
阶段有着不同的编译器和解释器。
这些东西的实现又反过来影响了这门语言的设计，
帮助发现那些性能不足、矛盾或者难以实现且得不偿失的特性。
(by highlighting misfeatures,contradictions,or features
of difficult implementation and little benefit)
这门语言通过反复的改进，成为一个衔接顺畅且统一的规范语言。
（翻译待改善）。

Perl6是一门通用，直观灵活的语言。它融合了如程序化（procedural），
面向对象，和函数式编程等众多范式；同时也为文本解析提供了强大的工具。

这本书正在书写中。已经发布的版本中依然包许多TODO的注释，这些是我们在
正式刊印本书前要做的。我们保留TODO是因为他们可以为读者和我们提供一个有用
的提示，让我们知道那些地方需要改善和完成。
尽管如此，我们仍然要祈求读者的宽容和理解。

** 1.1 Audience 读者人群
这本书主要是为那些想学习Perl6的人准备的。
它只是一系列的学习指南，而不是综合的参考手册。
尽快不要求对Perl有一定的认识，但是我们依然希望读者能够有一些使用其他编程语言的
经验。

** 1.2 本书的结构
每一章以一个合理而完整的例子来阐述本章的主题。
我们希望通过解释每一章中真实的程序，能够通过这些例子来展现如何使用这些特色，技巧和惯用语。
我们的目标是把Perl6的特点在程序中表现出来，这样读者就可以自己写出地道的Perl6程序，
而不是写出像其它语言的程序。
** 1.3 Perl6和Perl5的关系
Perl6是Perl大家族中新的一员。从5到6的进化中，Perl6在语法和语义的兼容性
上有了很大的代沟。但是这并不意味着Perl5会消逝。实际上，恰恰相反，Perl5和
Perl6都有活跃的开发团队，正是他们铸造了这门语言。
Perl5的开发人员，都在保持兼容老版本Perl的基础上，用不同的方式来进行扩展。
而Perl6的开发人员，通过添加新的语法和语义上功能来让Perl这门语言更加的强大和
有更强的表现能力，而不用严格的考虑兼容Perl5以及以前的版本。

也许有些人会问，“既然是一门不同的语言为何还称之为Perl？”Perl不仅仅是一种语法。
而是一种理念（比如：做事情的方法不只有一种；让容易的事情更容易，不容易的事情可以实现）
；还是一种风俗（comprehensive testing,idioms);还是一座大厦（CPAN）；还是一个社群
（perl5-porters，perl6-language)。不论Perl5还是Perl6都在不同程度上烙有这些基因。
同样，Perl也是包容的。如同Perl从其它语言借鉴好的想法一样，Perl5和Perl6也共享着一些特性。

** 1.4 Perl 6 的实现
Perl 6是一种规范。任何一种能完整通过官方测试的实现方式都可以把自己称之为Perl6。
现在已经存在几种不同的实现形式，他们的完备性各不相同。本书的所有例子都是在
Rakudo Perl 6 编译器上运行，但是这并不是说他们只能在Rakudo上才能运行，任何一个
成熟的Perl 6的实现都可以运行这些例子。最后祝您好运，如同Perl 6 团队经常说的-玩的开心。

** 1.5 安装Rakudo

